Numpy
---

In [2]:
import numpy as np
import sys

In [3]:
sys.version

'3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]'

In [4]:
np.__version__

'2.3.3'

Arrays vs Python list

In [5]:
%timeit python_list = list(range(1_000_000))

97.8 ms ± 15.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
%timeit numpy_array = np.arange(1_000_000)

7.95 ms ± 820 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Core Fundamental

In [11]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [13]:
a2 = np.arange(1,10)
a2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a3 = np.arange(1,10, 2)
a3

array([1, 3, 5, 7, 9])

In [15]:
a4 = np.arange(1,10, 3)
a4

array([1, 4, 7])

In [21]:
a5 = np.linspace(1,5,3)
a5

array([1., 3., 5.])

Placeholders

In [22]:
p1 = np.zeros((3,3))
p1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
p2 = np.ones((3,3))
p2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
a5.shape

(3,)

In [25]:
p2.shape

(3, 3)

In [26]:
p2.dtype

dtype('float64')

In [27]:
a5.dtype

dtype('float64')

In [28]:
a3.dtype

dtype('int64')

Indexing and Slicing

In [29]:
a3

array([1, 3, 5, 7, 9])

In [30]:
# [start: end: step]

a3[2:4]

array([5, 7])

In [31]:
a3[0:4:2]

array([1, 5])

In [32]:
a3[a3>5]

array([7, 9])

In [33]:
a3[a3 < 7]

array([1, 3, 5])

Broadcasting

In [34]:
p1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
((p1 + 5)* 2)/5

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [38]:
a3

array([1, 3, 5, 7, 9])

In [39]:
a3**2

array([ 1,  9, 25, 49, 81])

In [40]:
a3 - 5

array([-4, -2,  0,  2,  4])

Operations

In [42]:
a3

array([1, 3, 5, 7, 9])

In [41]:
a3.sum()

np.int64(25)

In [43]:
a3.mean()

np.float64(5.0)

In [45]:
a3.std().round(2)

np.float64(2.83)

In [46]:
a3.min()

np.int64(1)

In [47]:
a3.max()

np.int64(9)

In [48]:
a3.argmax()

np.int64(4)

Reshaping

In [49]:
a4 = np.arange(1,30,3)

In [50]:
a4

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [53]:
a5 = np.arange(0,10)
a5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshaping

In [54]:
a4.reshape(2,5)

array([[ 1,  4,  7, 10, 13],
       [16, 19, 22, 25, 28]])

In [55]:
a5.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
a4.reshape(2,5) @ a5.reshape(5,2)

array([[200, 235],
       [500, 610]])

In [58]:
dot1 = np.dot(a4.reshape(2,5), a5.reshape(5,2))

Ravel

In [61]:
ravel1 = np.ravel(dot1)
ravel1

array([200, 235, 500, 610])

In [62]:
ravel1[2] = 9000

In [63]:
dot1

array([[ 200,  235],
       [9000,  610]])

Flatten

In [ ]:
arr = np.array([[1,2,3],
               [4,5,6]])

flatten_arr = arr.flatten()
print(flatten_arr)

[1 2 3 4 5 6]


In [66]:
flatten_arr[4] = 19
print(flatten_arr)
print(arr)

[ 1  2  3  4 19  6]
[[1 2 3]
 [4 5 6]]


hstack

In [67]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result_1d = np.hstack((a, b))
result_1d

array([1, 2, 3, 4, 5, 6])

In [68]:
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])
result_2d = np.hstack((c, d))
print(f"2D example:\n{result_2d}")

2D example:
[[1 2 5 6]
 [3 4 7 8]]


vstack

In [69]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_1d = np.vstack((a, b))
stacked_1d

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])
stacked_2d = np.vstack((array1, array2))
stacked_2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

split

In [ ]:
np.split(array, indices_or_sections=, axis=)

In [71]:
arr_1d = np.array([0, 1, 2, 3, 4, 5])
# Split in 3 equal parts
sub_arrays_equal = np.split(arr_1d, 3)
sub_arrays_equal

[array([0, 1]), array([2, 3]), array([4, 5])]

In [73]:
arr_1d = np.arange(1,6)
arr_1d

array([1, 2, 3, 4, 5])

In [74]:
np.split(arr_1d, 3)

ValueError: array split does not result in an equal division

In [76]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

sub_arrays_rows = np.split(arr_2d, 3, axis=0)
sub_arrays_rows

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [79]:
sub_arrays_cols = np.split(arr_2d, [1], axis=1)
sub_arrays_cols

[array([[1],
        [4],
        [7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]])]

Copy and View

In [80]:
original_array = np.array([1, 2, 3, 4, 5])
original_array

array([1, 2, 3, 4, 5])

In [81]:
view_array = original_array[1:4]
view_array

array([2, 3, 4])

In [82]:
view_array[0] = 99

In [84]:
view_array

array([99,  3,  4])

In [83]:
original_array

array([ 1, 99,  3,  4,  5])

In [85]:
copy_array = original_array.copy()
copy_array

array([ 1, 99,  3,  4,  5])

In [86]:
copy_array[1] = 2

In [87]:
copy_array

array([1, 2, 3, 4, 5])

In [88]:
original_array

array([ 1, 99,  3,  4,  5])